server:
  port: 8081

spring:
  application:
    name: gateway

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:risk}
    username: ${DB_USER:risk}
    password: ${DB_PASSWORD:risk}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: gateway

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: gateway
    liquibase-schema: gateway

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all

logging:
  level:
    com.riskscoring: DEBUG